server:
  port: 8080

spring:
  application:
    name: example
  datasource:
    username: ${USER}
    password: 123123
    url: jdbc:postgresql://localhost:5432/example
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
